"""Shared utility functions for milvus-ingest.

This module provides common helper functions used across multiple modules,
reducing code duplication and improving maintainability.
"""

from __future__ import annotations

from typing import Any


def is_bm25_output_field(field_name: str, schema: dict[str, Any]) -> bool:
    """Check if a field is a BM25 function output field.

    BM25 function output fields are auto-generated by Milvus and should be
    skipped during data generation and insertion.

    Args:
        field_name: Name of the field to check.
        schema: Schema dict containing 'functions' key with function definitions.
            Can be the direct schema or a metadata dict with nested 'schema' key.

    Returns:
        True if the field is a BM25 function output field, False otherwise.
    """
    # Handle both direct schema and metadata dict with nested schema
    if "schema" in schema and isinstance(schema["schema"], dict):
        functions = schema["schema"].get("functions", [])
    else:
        functions = schema.get("functions", [])

    for func in functions:
        if func.get("type") == "BM25" and field_name in func.get(
            "output_field_names", []
        ):
            return True
    return False


def find_partition_key_field(fields: list[dict[str, Any]]) -> dict[str, Any] | None:
    """Find the partition key field in schema fields.

    Args:
        fields: List of field definitions from schema.

    Returns:
        The partition key field definition, or None if not found.
    """
    for field in fields:
        if field.get("is_partition_key", False):
            return field
    return None


def find_primary_key_field(fields: list[dict[str, Any]]) -> dict[str, Any] | None:
    """Find the primary key field in schema fields.

    Args:
        fields: List of field definitions from schema.

    Returns:
        The primary key field definition, or None if not found.
    """
    for field in fields:
        if field.get("is_primary", False):
            return field
    return None


def get_field_by_name(
    fields: list[dict[str, Any]], field_name: str
) -> dict[str, Any] | None:
    """Get a field definition by name.

    Args:
        fields: List of field definitions from schema.
        field_name: Name of the field to find.

    Returns:
        The field definition, or None if not found.
    """
    for field in fields:
        if field.get("name") == field_name:
            return field
    return None


def is_vector_field(field_type: str) -> bool:
    """Check if a field type is a vector type.

    Args:
        field_type: The field type string.

    Returns:
        True if the field type is a vector type.
    """
    return "Vector" in field_type


def is_nullable_field(field: dict[str, Any]) -> bool:
    """Check if a field is nullable.

    Args:
        field: Field definition dict.

    Returns:
        True if the field is nullable.
    """
    return field.get("nullable", False)


def is_auto_id_field(field: dict[str, Any]) -> bool:
    """Check if a field is an auto_id field.

    Args:
        field: Field definition dict.

    Returns:
        True if the field is an auto_id field.
    """
    return field.get("auto_id", False)


__all__ = [
    "is_bm25_output_field",
    "find_partition_key_field",
    "find_primary_key_field",
    "get_field_by_name",
    "is_vector_field",
    "is_nullable_field",
    "is_auto_id_field",
]
